[colors.primary]
background = '#181825'
foreground = '#cdd6f4'

[colors.selection]
text = '#cdd6f4'
background = '#6e5a2f'

[colors.cursor]
text = '#181825'
cursor = '#f9e2af'

[colors.normal]
black   = '#181825'
red     = '#e44b7b'
green   = '#95d66e'
yellow  = '#dbb07b'
blue    = '#b89449'
magenta = '#baac8e'
cyan    = '#f9e2af'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f8c'
green   = '#a7e086'
yellow  = '#e8c497'
blue    = '#e8d2a3'
magenta = '#9f7144'
cyan    = '#8a7c45'
white   = '#ffffff'
